### PR TITLE
dernière version équipe 1

### PR DESCRIPTION
**Pull request by elisagm**
accord de Romu pour s'ajouter au monde

### CODE REVIEW

**Comment by massimotisi** [comment]
You are trying to remove `CACAO2018/src/abstraction/eq1DIST/IVenteConso.java` but you still use it

**Comment by leo-petitjean** [comment]
Ok

**Comment by massimotisi** [comment]
You have not pushed the change to team 6

**Comment by massimotisi** [comment]
IndexOutOfBoundsException during next

**Comment by massimotisi** [comment]
IndexOutOfBoundsException during next

**Comment by leo-petitjean** [comment]
Ok

**Comment by massimotisi** [comment]
Conflict with the latest accepted pull request

**Comment by massimotisi** [comment]
I need again the ok of  @leo-petitjean

**Comment by leo-petitjean** [comment]
Ok

**Pull request merged**
