### PR TITLE
EQ4 suppression du code deprecated

### PR DESCRIPTION
**Pull request by Carlivoix**

### CODE REVIEW

**Comment by massimotisi** [comment]
I think that `/CACAO2018/src/abstraction/eq4TRAN/IVendeurChoco.java` should be deprecated

**Comment by massimotisi** [comment]
I'm not accepting before you deprecate and stop using `abstraction.eq4TRAN.IVendeurChoco`

**Comment by massimotisi** [comment]
`abstraction.eq4TRAN.IVendeurChoco` is still used in `Vendeur`

**Comment by Carlivoix** [comment]
We can't see any crossed code in Vendeur

**Comment by massimotisi** [comment]
Please remove the import of `abstraction.eq4TRAN.IVendeurChoco`

**Pull request merged**
