### PR TITLE
Interface producteur 2 <-> producteur 3

### PR DESCRIPTION
**Pull request by AgatheChevalier**

### CODE REVIEW

**Comment by massimotisi** [comment]
Not accepting because it changes the file `CACAO2018/bin/.gitignore`.
Please revert it to its original form `https://github.com/CACAO2018/CACAO2018/blob/master/CACAO2018/bin/.gitignore`

**Comment by massimotisi** [comment]
almost, you are missing a "newline" at the end of the file bin/.gitignore

**Comment by AgatheChevalier** [comment]
problem fixed ? @massimotisi

**Comment by massimotisi** [comment]
yes, now it's fixed

PS. you don't need to ask me, you can see that your pull request is good if all checks are green, and you can also see the list of the modifications included in the pull request in the "Files Changed" tab at the top

**Comment by massimotisi** [comment]
Not accepting because it changes the file `CACAO2018/bin/.gitignore`.
Please revert it to its original form `https://github.com/CACAO2018/CACAO2018/blob/master/CACAO2018/bin/.gitignore`.

**Pull request merged**
