### PR TITLE
Equipe1

### PR DESCRIPTION
**Pull request by elisagm**

### CODE REVIEW

**Comment by massimotisi** [comment]
as you can see from the automatic checks: 
1) you are touching some files that you can't change: `.classpath`, `CACAO2018/bin/.gitignore`
2) you can't create a new package `abstraction\ClientsFinaux`
3) you are changing a file from equipe6, so you need their approval
4) you need to synchronize with the main repository because your changes are in conflict with some pull requests from other groups

**Comment by leo-petitjean** [comment]
euke

**Comment by leo-petitjean** [comment]
ok

**Comment by massimotisi** [comment]
still problems with .gitignore and Monde

**Comment by massimotisi** [comment]
...and now conflicts to solve by synchronizing with my repository

**Comment by massimotisi** [comment]
This pull request is waiting for a lot of time...

**Comment by massimotisi** [comment]
I will freeze the v1 at 19:00 today. If you don't fix the conflicts none of your code will be included.

**Comment by elisagm** [comment]
C'est ok pour l'équipe 1

**Pull request merged**
